# pandoc calls this "metadata-file"

# main settings

title: A Survey of German Diathesis
author: Michael Cysouw
date: \today

mainfont: Libertinus Serif
top-level-division: chapter
toc-title: Table of Contents

# crossref settings

secPrefix: 
  - Section
  - Sections
tblPrefix:
  - Table
  - Tables
figPrefix:
  - Figure
  - Figures
pairDelim: "-"
chapters: true

# citeproc settings

bibliography: /Users/cysouw/Documents/Bibdesk/michaellibrary.bib
citation-style: /Users/cysouw/Documents/Bibdesk/unified.csl
reference-section-title: References
link-citations: true

# latex settings

documentclass: book
classoption: twoside
papersize: a4
indent: true

header-includes:
# Fallback font does not work in XeLateX, so all font problems have to be specified manually, e.g. like this
# - \newfontfamily{\greek}{Times New Roman}
# Page layout
- \usepackage[margin=4cm]{geometry}
- \usepackage{float}
- \floatplacement{figure}{htb} # remove latex "p" option: don't let figures take over the whole page. Default pandoc to latex uses [htbp]
# TOC specificifaction
- \usepackage{tocloft}
- \renewcommand{\cftsubsecfont}{\scriptsize} # small subsection in TOC
# Example numbering
- \usepackage{linguex}
- \renewcommand{\firstrefdash}{\,} # small non-breaking space after number of examples
- \renewcommand{\Exarabic}{\thechapter.\arabic} # add chapter number to examples
# Reset counters
- \usepackage{chngcntr}
- \counterwithin{ExNo}{chapter} # restart numbering of examples each chapter
