# main settings

mainfont: Libertinus Serif
top-level-division: chapter
toc-title: Contents
lang: en-GB # important for hyphenation

# pandoc-crossref settings

secPrefix: 
  - Section
  - Sections
tblPrefix:
  - Table
  - Tables
figPrefix:
  - Figure
  - Figures
pairDelim: "-"
chapters: true
linkReferences: true

# pandoc-ling settings

addChapterNumber: true
xrefSuffixSep: " "
latexPackage: gb4e
formatGloss: true

# count-para settings

resetAtChapter: true

# citeproc settings

bibliography: /Users/cysouw/Documents/Bibdesk/michaellibrary.bib
citation-style: /Users/cysouw/Documents/Bibdesk/unified.csl
reference-section-title: References
link-citations: true

# latex settings

documentclass: book
classoption: twoside
papersize: a4
indent: true
margin-left: 4cm
margin-right: 4cm

